### ISSUE TITLE
 java.lang.UnsatisfiedLinkError:

### ISSUE THREAD

**Issue by ravisahu** [KAlO2/PerfectShow#1]
Hello @KAlO2,

Please check below log report.

java.lang.UnsatisfiedLinkError: No implementation found for android.graphics.PointF[][] com.cloudream.ishow.algorithm.Feature.nativeDetectFace(android.graphics.Bitmap, java.lang.String, java.lang.String) (tried Java_com_cloudream_ishow_algorithm_Feature_nativeDetectFace and Java_com_cloudream_ishow_algorithm_Feature_nativeDetectFace__Landroid_graphics_Bitmap_2Ljava_lang_String_2Ljava_lang_String_2)
01-12 15:55:23.753: E/AndroidRuntime(9369): 	at com.cloudream.ishow.algorithm.Feature.nativeDetectFace(Native Method)
01-12 15:55:23.753: E/AndroidRuntime(9369): 	at com.cloudream.ishow.algorithm.Feature.detectFace(Feature.java:84)
01-12 15:55:23.753: E/AndroidRuntime(9369): 	at com.cloudream.ishow.app.MakeupActivity.onCreate(MakeupActivity.java:299)
01-12 15:55:23.753: E/AndroidRuntime(9369): 	at android.app.Activity.performCreate(Activity.java:6876)
01-12 15:55:23.753: E/AndroidRuntime(9369): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
01-12 15:55:23.753: E/AndroidRuntime(9369): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
01-12 15:55:23.753: E/AndroidRuntime(9369): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
01-12 15:55:23.753: E/AndroidRuntime(9369): 	at android.app.ActivityThread.access$1100(ActivityThread.java:221)
01-12 15:55:23.753: E/AndroidRuntime(9369): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
01-12 15:55:23.753: E/AndroidRuntime(9369): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-12 15:55:23.753: E/AndroidRuntime(9369): 	at android.os.Looper.loop(Looper.java:158)
01-12 15:55:23.753: E/AndroidRuntime(9369): 	at android.app.ActivityThread.main(ActivityThread.java:7224)
01-12 15:55:23.753: E/AndroidRuntime(9369): 	at java.lang.reflect.Method.invoke(Native Method)
01-12 15:55:23.753: E/AndroidRuntime(9369): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
01-12 15:55:23.753: E/AndroidRuntime(9369): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

Please help me to resolve this issue.

**Comment by KAlO2** [comment]
Have you made the JNI part?

**Comment by ravisahu** [comment]
Yes.I am able to create two .so (opencv_java3,venus)

**Comment by ravisahu** [comment]
@KAlO2 - Yes, libvenus.so is  generated.

**Comment by KAlO2** [comment]
@ravisahu Did you update the code to the newest version? Because previously I use detectFace() to detect single face, and later I changed the method signature to detect multiple faces.

**Comment by adasharma** [comment]
@KAlO2 I am also facing issue getting run this project. I am trying to use Android studio and latest cMake and cMakeList.txt way of native integration. Are you going to migrate this eclipse project to android studio project ?

**Comment by KAlO2** [comment]
I create the APK [here](http://pan.baidu.com/s/1c2f2ltI), in case others want to try it. 
By the way, I'm still working on it, especially on the makeup algorithm, some UI bugs may happens.

**Comment by KAlO2** [comment]
Fixed in [ineb2da93aef2f607600d979e848a38bbcc15990f1](https://github.com/KAlO2/PerfectShow/commit/eb2da93aef2f607600d979e848a38bbcc15990f1)
now detectFace() detects only one dominant face, detectFaces() detects mutiple faces.

**Comment by elfifo4** [comment]
I still see this error after picking an image from gallery (Makeup button was clicked):

2019-10-28 11:12:22.900 345-345/com.wonderful.ishow E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.wonderful.ishow, PID: 345
    java.lang.UnsatisfiedLinkError: No implementation found for android.graphics.PointF[] com.wonderful.ishow.makeup.Feature.nativeDetectFace(android.graphics.Bitmap, java.lang.String, java.lang.String) (tried Java_com_wonderful_ishow_makeup_Feature_nativeDetectFace and Java_com_wonderful_ishow_makeup_Feature_nativeDetectFace__Landroid_graphics_Bitmap_2Ljava_lang_String_2Ljava_lang_String_2)
        at com.wonderful.ishow.makeup.Feature.nativeDetectFace(Native Method)
        at com.wonderful.ishow.makeup.Feature.detectFace(Feature.java:86)
        at com.wonderful.ishow.app.MakeupActivity.initData(MakeupActivity.java:301)
        at com.wonderful.ishow.app.MakeupActivity.onCreate(MakeupActivity.java:256)


and what about the other buttons?
Collage, Crop, Camera, Color, Effect
they do nothing.

Thanks
